import { sql } from "drizzle-orm";
import {
  bigint,
  check,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { user } from "./auth-schema";

// Better Auth tables (user, session, account, verification) — generated by
// `npx @better-auth/cli generate`; regenerate rather than hand-editing.
export * from "./auth-schema";

export const githubInstallations = pgTable(
  "github_installations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    // GitHub's numeric installation id. UNIQUE is the ownership guarantee:
    // one installation can only ever be claimed by one DoFast user.
    installationId: bigint("installation_id", { mode: "number" })
      .notNull()
      .unique(),
    accountLogin: text("account_login").notNull(),
    accountType: text("account_type").notNull(),
    repositorySelection: text("repository_selection"), // "all" | "selected"
    permissions: jsonb("permissions"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    suspendedAt: timestamp("suspended_at", { withTimezone: true }),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
  },
  (t) => [index("github_installations_user_id_idx").on(t.userId)]
);

export const waitlistSignups = pgTable("waitlist_signups", {
  id: uuid("id").primaryKey().defaultRandom(),
  // Stored normalized (trimmed + lowercased); uniqueness relies on it.
  email: text("email").notNull().unique(),
  source: text("source").notNull().default("landing_page"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const auditLog = pgTable("audit_log", {
  id: uuid("id").primaryKey().defaultRandom(),
  // Plain text until the auth tables land in Milestone 2.
  userId: text("user_id"),
  siteId: text("site_id"),
  action: text("action").notNull(),
  detail: jsonb("detail"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const sites = pgTable(
  "sites",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    installationId: bigint("installation_id", { mode: "number" })
      .notNull()
      .references(() => githubInstallations.installationId, {
        onDelete: "cascade",
      }),
    // GitHub's numeric repo id — stable across renames; uniqueness per user.
    repoId: bigint("repo_id", { mode: "number" }).notNull(),
    repoFullName: text("repo_full_name").notNull(),
    defaultBranch: text("default_branch").notNull(),
    framework: text("framework").notNull(), // "nextjs" | "react"
    status: text("status").notNull().default("active"), // "active" | "disconnected"
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    disconnectedAt: timestamp("disconnected_at", { withTimezone: true }),
  },
  (t) => [
    uniqueIndex("sites_user_repo_unique").on(t.userId, t.repoId),
    index("sites_user_id_idx").on(t.userId),
    index("sites_installation_id_idx").on(t.installationId),
  ]
);

export const repoSnapshots = pgTable(
  "repo_snapshots",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    siteId: uuid("site_id")
      .notNull()
      .references(() => sites.id, { onDelete: "cascade" }),
    // Empty string only on the failed placeholder row (no build ever succeeded).
    commitSha: text("commit_sha").notNull(),
    ref: text("ref").notNull(),
    status: text("status").notNull(), // "ready" | "truncated" | "failed"
    fileCount: integer("file_count").notNull().default(0),
    skippedCount: integer("skipped_count").notNull().default(0),
    totalSize: bigint("total_size", { mode: "number" }).notNull().default(0),
    fileIndex: jsonb("file_index").notNull(),
    // Transient refresh failures never destroy the last-known-good snapshot;
    // they are recorded here alongside it.
    refreshError: text("refresh_error"),
    refreshFailedAt: timestamp("refresh_failed_at", { withTimezone: true }),
    // Build start time — used to prevent a slower, older build from
    // overwriting a newer snapshot (upsert is conditioned on it).
    indexedAt: timestamp("indexed_at", { withTimezone: true }).notNull(),
    headCheckedAt: timestamp("head_checked_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("repo_snapshots_site_id_unique").on(t.siteId),
    check(
      "repo_snapshots_status_check",
      sql`${t.status} in ('ready', 'truncated', 'failed')`
    ),
    check("repo_snapshots_file_count_check", sql`${t.fileCount} >= 0`),
    check("repo_snapshots_skipped_count_check", sql`${t.skippedCount} >= 0`),
    check("repo_snapshots_total_size_check", sql`${t.totalSize} >= 0`),
  ]
);
